### ISSUE TITLE
Removing non-async methods?

### ISSUE THREAD

**Issue by mhinze** [mhinze/ShortBus#16]
```
public interface IMediator
{
  Task<Response<TResult>> RequestAsync<TResult>(IAsyncQuery<TResult> query);
  Task<Response<TResult>> SendAsync<TResult>(IAsyncCommand<TResult> command);
}
```

If this is acceptable, what about this?

```
public interface IMediator
{
  Task<Response<TResult>> HandleAsync<TResult>(IOperation<TResult> op);
}
```

**Comment by zachariahyoung** [comment]
Would this still work if you only had .net 4.0?  I have not worked with async in .net 4.5 yet.

Also I think we should add something for eventhandlers.

**Comment by mhinze** [comment]
I do not know what .net 4.0 is like with Shortbus.  I am open to PRs that let us take advantage of the nuget multiple framework version support stuff.  I don't think I have a machine without 4.5 on it at this point.

**Comment by zachariahyoung** [comment]
Are you running VS 12 or 13?  All I have is VS 10 and I would like to contribute to the project so maybe I can check out VS express.

Maybe somebody has a free MSDN license for me. :)

**Comment by zachariahyoung** [comment]
@mhinze So what's your thinking on this?  Maybe we could have a HandleAsync and Handle.

**Comment by mhinze** [comment]
We're still exploring and using ICommand<T> so.. we'll get here but I dont feel pressure to move fast. I think the best approach is to support multiple framework versions via nuget but I dont have it in me to work on that this week.  A little swamped.
