### ISSUE TITLE
CommandHandler as abstract class

### ISSUE THREAD

**Issue by zachariahyoung** [mhinze/ShortBus#18]
When we have the CommandHandler as a abstract class we can't have a single class with multiple handlers.  I was hoping to have one handler class per entity .

Something like this.

CommentHandler : CommandHandler<CreateComment>, CommandHandler<CreateComment>

Does creating class like this make sense or should I bee create a single handler class for each command?

If not should we thinking the abstract class

**Comment by mhinze** [comment]
You can still implement the interface, the ABC is very thin..

**Comment by jrnail23** [comment]
Yep, the abstract CommandHandler is really just a convenience thing, to save you from having to remember to 

``` C#
return UnitType.Default;
```

at the end of each handler.
