### ISSUE TITLE
ShortBus 3.0 simple excample and basecontroller

### ISSUE THREAD

**Issue by michaelvolz** [mhinze/ShortBus#28]
Hi,

is ShortBus 3.0 already usable and do you have a little example of how to use it in combination with your basecontroller.

That would be really appreciated. Thanks in advance. 

Nice project!

**Comment by josephwoodward** [comment]
I'm really interested in seeing a little example too. I've tried to put an example together based on your recent changes but didn't get very far.

Many thanks for all of your hard work.

**Comment by michaelvolz** [comment]
I did a little work and updated the source code to StructureMap 3.0. 
You can get some inspirations from this Gist https://gist.github.com/michaelvolz/1f5dab543d5d687e522d

Works fine for me actually.
