### ISSUE TITLE
The base class or interface of 'ShortBus.Response' could not be resolved or is invalid

### ISSUE THREAD

**Issue by lruckman** [mhinze/ShortBus#34]
Using latest NuGet I'm getting the following error when compiling:

Error   4   The base class or interface of 'ShortBus.Response' could not be resolved or is invalid   <removed>\packages\ShortBus.3.0.46-beta\lib\ShortBus.dll

Is this a known issue?

I have the following packages installed:

<package id="ShortBus" version="3.0.46-beta" targetFramework="net45" />
 <package id="ShortBus.Markers" version="3.0.43-beta" targetFramework="net45" />
 <package id="ShortBus.StructureMap" version="3.0.48-beta" targetFramework="net45" />

**Comment by lruckman** [comment]
Built from source and the problem went away.

**Comment by FilipDeVos** [comment]
If you install shortbus with this command you won't have the issue:

```
    install-package shortbus -pre -DependencyVersion Highest
```

**Comment by lruckman** [comment]
Very helpful, thanks!
